data <- read.table("power.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
date <- strptime(paste(data_subset$Date, data_subset$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
data_subset <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
G_p <- as.numeric(data_subset$Global_active_power)
G_r <- as.numeric(data_subset$Global_reactive_power)
voltage <- as.numeric(data_subset$Voltage)
Meter1 <- as.numeric(data_subset$Sub_metering_1)
Meter2 <- as.numeric(data_subset$Sub_metering_2)
Meter3 <- as.numeric(data_subset$Sub_metering_3)


png("plot4.png")
par(mfrow = c(2, 2))
plot(date, G_p, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(date, Meter1, type="l", ylab="Energy Submetering", xlab="")
lines(date, Meter2, type="l", col="red")
lines(date, Meter3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(date, G_r, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()